server:
  port: 8011

  compression:
    enabled: true
    mime-types: application/json

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: ["health", "info", "logfile", "loggers", "scheduledtasks", "flyway", "prometheus"]
    jmx:
      exposure:
        include: "*"

job:
  quartz:
    cron: 0 0/23 * * * ?

http:
  maxTotal: 100
  defaultMaxPerRoute: 20
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 5000
  staleConnectionCheckEnabled: true

shiro:
  loginUrl: /login
  successUrl: /
  unauthorizedUrl: /err

spring:
  application:
    name: starter_api
  mvc:
    throw-exception-if-no-handler-found: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: files
      max-file-size: 20MB
      max-request-size: 20MB

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/starter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: dba
    password: dba
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 100
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 0

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    in-memory: false
    packages:
      trust-all: true
    pool:
      enabled: false

logging:
  level:
    com.hello: info
  file:
    path: logs
    name: logs/starter.log
    max-size: 10MB
    max-history: 7
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
